[package]
name = "temp_r"
version = "0.1.0"
authors = ["Aswasa <tonylipin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
temp_convertor = "0.1.0"

[[bin]]
name = "TempR"
path = "main.rs"
